package com.example.myapplicationmyday.data

import android.util.Log
import androidx.lifecycle.LiveData
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.ktx.firestore
import com.google.firebase.ktx.Firebase
import kotlinx.coroutines.tasks.await

class DiaryRepository(private val diaryDao: DiaryDao) {
    private val firestore: FirebaseFirestore = Firebase.firestore
    val allEntries: LiveData<List<DiaryEntry>> = diaryDao.getAllEntries()
    
    suspend fun insert(entry: DiaryEntry): Long {
        val localId = diaryDao.insert(entry)
        
        // Sync to Firestore
        if (entry.userId.isNotEmpty()) {
            try {
                val docRef = firestore.collection("users")
                    .document(entry.userId)
                    .collection("diary_entries")
                    .add(mapOf(
                        "title" to entry.title,
                        "content" to entry.content,
                        "date" to entry.date,
                        "createdAt" to entry.createdAt,
                        "userId" to entry.userId
                    ))
                    .await()
                
                // Update local entry with Firestore ID
                val updatedEntry = entry.copy(id = localId, firestoreId = docRef.id)
                diaryDao.update(updatedEntry)
                Log.d("DiaryRepository", "Entry synced to Firestore: ${docRef.id}")
            } catch (e: Exception) {
                Log.e("DiaryRepository", "Error syncing to Firestore", e)
            }
        }
        
        return localId
    }
    
    suspend fun update(entry: DiaryEntry) {
        diaryDao.update(entry)
        
        // Sync to Firestore
        if (entry.userId.isNotEmpty() && entry.firestoreId.isNotEmpty()) {
            try {
                firestore.collection("users")
                    .document(entry.userId)
                    .collection("diary_entries")
                    .document(entry.firestoreId)
                    .update(mapOf(
                        "title" to entry.title,
                        "content" to entry.content,
                        "date" to entry.date
                    ))
                    .await()
                Log.d("DiaryRepository", "Entry updated in Firestore: ${entry.firestoreId}")
            } catch (e: Exception) {
                Log.e("DiaryRepository", "Error updating Firestore", e)
            }
        }
    }
    
    suspend fun delete(entry: DiaryEntry) {
        diaryDao.delete(entry)
        
        // Delete from Firestore
        if (entry.userId.isNotEmpty() && entry.firestoreId.isNotEmpty()) {
            try {
                firestore.collection("users")
                    .document(entry.userId)
                    .collection("diary_entries")
                    .document(entry.firestoreId)
                    .delete()
                    .await()
                Log.d("DiaryRepository", "Entry deleted from Firestore: ${entry.firestoreId}")
            } catch (e: Exception) {
                Log.e("DiaryRepository", "Error deleting from Firestore", e)
            }
        }
    }
    
    suspend fun getEntryById(id: Long): DiaryEntry? {
        return diaryDao.getEntryById(id)
    }
    
    suspend fun syncFromFirestore(userId: String) {
        if (userId.isEmpty()) return
        
        try {
            val snapshot = firestore.collection("users")
                .document(userId)
                .collection("diary_entries")
                .get()
                .await()
            
            val firestoreEntries = snapshot.documents.mapNotNull { doc ->
                DiaryEntry(
                    id = 0, // Will be auto-generated by Room
                    title = doc.getString("title") ?: "",
                    content = doc.getString("content") ?: "",
                    date = doc.getLong("date") ?: System.currentTimeMillis(),
                    createdAt = doc.getLong("createdAt") ?: System.currentTimeMillis(),
                    userId = doc.getString("userId") ?: userId,
                    firestoreId = doc.id
                )
            }
            
            // Get local entries for this user
            val localEntries = diaryDao.getEntriesByUserId(userId)
            val localFirestoreIds = localEntries.mapNotNull { it.firestoreId }.toSet()
            
            // Insert entries that don't exist locally
            firestoreEntries.forEach { firestoreEntry ->
                if (firestoreEntry.firestoreId !in localFirestoreIds) {
                    diaryDao.insert(firestoreEntry)
                    Log.d("DiaryRepository", "Synced entry from Firestore: ${firestoreEntry.firestoreId}")
                }
            }
            
            Log.d("DiaryRepository", "Sync completed: ${firestoreEntries.size} entries from Firestore")
        } catch (e: Exception) {
            Log.e("DiaryRepository", "Error syncing from Firestore", e)
        }
    }
}
